fedora-sysv/initscripts

- rc.d/init.d/functions
On cgroup2 systems the current test for systemd doesn't work, as the cgroup hierarchy is setup differently. This results in the `systemctl_redirect` function not working properly, which breaks the redirection logic and leads to subtle bugs and general sadness. This PR changes the logic to just check for `/run/systemd/system`, which is independent from the cgroup hierarchy and is the recommended way to detect systemd by upstream.
> functions: more reliable systemd detection logic

- sysconfig/network-scripts/ifdown-ipv6
- sysconfig/network-scripts/ifup-ipv6
- sysconfig/network-scripts/init.ipv6-global
network-scripts makes odd assumptions, like if I don't want SLAAC (i.e.
if I turn off AUTOCONF) that I also don't want RA. This is not true,
it's common to have a static local address, but to get my gateway
through RA.
This is one solution. I will also be sending a more specific solution to
enable the above directly, but having a way to tell network-scripts
to not mess with systctls seems generally useful.
> Provide a mechanism to prevent network-scripts from messing with sysctls

- sysconfig/network-scripts/ifup-ipv6
It's reasonable (and common) to assign static addresses while still
wanting to get your default gw from your router. The assumption that not
wanting SLAAC means not wanting RA is flawed, but I don't want to break
backwards compatability, so I'm adding an additional option.
> Allow someone to keep accept_ra on while using static addresses.

- sysconfig/network-scripts/ifdown-ipv6
- sysconfig/network-scripts/ifup-ipv6
- sysconfig/network-scripts/init.ipv6-global
- sysconfig/network-scripts/network-functions-ipv6
The network-scripts are a mix of tabs and spaces (!!) as well as
completely inconsistent indentation (some 2, some 4).
This is a series of 3 patches to move the entire of network-scripts to
2-space indentation for consistency so I can develop on the codebase
without my brain bleeding. I don't feel strongly about 2 vs 4... 2 was
just most common in the first file I picked, so I used that.
This set is in 3 sets for easier reviewing and easier reverting if
necessary:
* 1/3 - ipv6 files
* 2/3 - network-functions - it needed it's own
* 3/3 - ifup/ifdown files
> [1/3] Remove tabs and fix spacing: ipv6 scripts

- rc.d/init.d/functions
Fix style to be consistent with the one discussed in #3. No functional changes, actual diff minus whitespace below:
```
diff --git a/rc.d/init.d/functions b/rc.d/init.d/functions
index 3bad6f7..788902c 100644
--- a/rc.d/init.d/functions
+++ b/rc.d/init.d/functions
@@ -66,7 +66,8 @@ if [ -z "${CONSOLETYPE:-}" ]; then
fi
fi
-if [ -z "${NOLOCALE:-}" ] && [ -z "${LANGSH_SOURCED:-}" ] && [ -f /etc/sysconfig/i18n -o -f /etc/locale.conf ] ; then
+if [ -z "${NOLOCALE:-}" ] && [ -z "${LANGSH_SOURCED:-}" ] && \
+        [ -f /etc/sysconfig/i18n -o -f /etc/locale.conf ] ; then
. /etc/profile.d/lang.sh 2>/dev/null
unset LANGSH_SOURCED
@@ -222,8 +223,10 @@ daemon() {
nicelevel=0
while [ "$1" != "${1##[-+]}" ]; do
case $1 in
-	    '')    echo $"$0: Usage: daemon [+/-nicelevel] {program}" "[arg1]..."
- …
```
> functions: remove tabs and fix spacing

- rc.d/init.d/functions
- sysconfig/network-scripts/ifdown-eth
- sysconfig/network-scripts/ifup-aliases
- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/ifup-ippp
- sysconfig/network-scripts/ifup-ipv6
- sysconfig/network-scripts/ifup-sit
`is_true()` now recognizes value `1` as `true`,
`is_false()` now recognizes value `0` as `false`.
And I replaced the `[yY1]*` and `[nN0]*` occurences with those functions where possible.
> Support boolean values in is_true() & is_false() functions

- sysconfig/network-scripts/network-functions-ipv6
the diffs here are gonna be insane until the other PRs are merged, but the read diff is:
```
$ git show
commit 98f25d7807dee7a222f12476a0dd081f23703da3
Author: Phil Dibowitz <phil@ipom.com>
Date:   54 seconds ago
Fix typo'd variable in 6to4 cleanup
Thanks to shellcheck. :)
This is ontop of the whitespace PRs, those should go in first.
diff --git a/sysconfig/network-scripts/network-functions-ipv6 b/sysconfig/network-scripts/network-functions-ipv6
index 6ff6a76..2017e27 100644
--- a/sysconfig/network-scripts/network-functions-ipv6
+++ b/sysconfig/network-scripts/network-functions-ipv6
@@ -236,8 +236,8 @@ ipv6_cleanup_6to4_device() {
ipv6_test testonly || return 2
-    /sbin/ip -6 addr show dev $dev scope global permanent | awk '/\<inet6\>/ && $2 ~ /^2002:/ { print $2 }' | while read addr; …
```
> Fix for 6to4 bug

- service
When running:
```
service x restart
```
You get:
```
Redirecting to /bin/systemctl restart  x.service
```
With 2 spaces after restart.
This commits fixes that behaviour.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> service: avoid double spaces in systemctl commands

- sysconfig/network-scripts/ifup-eth
`ifup` can set _some_ route options. Today it's missing several and so, to set
something like `mtu` or `advmss` you have to do hacks like:
```
METRIC='10 mtu 1480'
```
which is sub-optimal. Rather than one-off add support for everything in the man
page, provide a hook for arbitrary extra route options.
> Add ability to specify arbitrary route options

- rc.d/init.d/functions
- sysconfig/network-scripts/ifup-aliases
Resolves RHBZ [#1340169](https://bugzilla.redhat.com/show_bug.cgi?id=1340169).
> [RHEL6] ifup-aliases: do not fail when only IPv6 address is specified

- sysconfig/network-scripts/ifup-aliases
Excerpt from [RHBZ #1320366](https://bugzilla.redhat.com/show_bug.cgi?id=1320366):
_`ifup-aliases` does not send gratuitous ARP updates when adding addresses.
When moving one or more aliases from one server to another, those IPs may not be
reachable for some time (depending on the ARP timeout on the upstream router)._
> ifup-aliases: send gratuitous ARPs when adding addresses

- sysconfig/network-scripts/ifup-post
This pull-request updates the `ifup-post` script to use `is_true()` &
`is_false()` functions, and adds option to set `NOROUTESET` variable to avoid
warnings about duplicate routes.
The suggestion for this came from Konrad Moson, in [RHBZ #950453](https://bugzilla.redhat.com/show_bug.cgi?id=950453).
> ifup-post: introduce new configuration option NOROUTESET

- rc.d/init.d/netconsole
This commit solves the issue described in [RHBZ #1278519](https://bugzilla.redhat.com/show_bug.cgi?id=1278519).
When the nameserver address lines are not present in `/etc/resolv.conf`, launching
`/etc/init.d/netconsole start` will result in this error:
``` shell
Server address not specified in /etc/sysconfig/netconsole
```
This was caused by using `hosts` command for domain name resolution. This is now
fixed by using `getent` command instead.
I have improved the patch provided in the RHBZ, here is the basic overview:
- To test if the `IPV6INIT` variable is set to `yes`, we are now using `is_true`
instead of grep-ing the value from `/etc/sysconfig/network` directly.
- Testing of initially set `$SYSLOGADDR` with regular expressions has been extended.
The regex for IPv6 has been added, and …
> netconsole: resolve domain name via 'getent' instead of 'hosts'

- rc.d/init.d/network
Nowadays /proc is a essential part of system and if it is on network,
we need to unmount it in shutdown dracut.
Also parsing /etc/mtab does not work anymore.
Fixes: rhbz#1369790
> network: don't put down network when /usr is remote-fs

- sysconfig/network-scripts/ifup-aliases
This is a backport of commit 55a50ebc591ebd0f4cfbb8ecc204fa20ee6a7368 to RHEL6, as sugested by Jan Scotka in [RHBZ #1275550](https://bugzilla.redhat.com/show_bug.cgi?id=1275550).
> ifup-aliases: don't return with error when arping fails

- sysconfig/network-scripts/ifup-aliases
This reverts commit 1cd4606a6de43fb9914f7099db2e30e3e2932dc0.
For more info see [RHBZ #1340169](https://bugzilla.redhat.com/show_bug.cgi?id=1340169#c8).
> Revert of "ifup-aliases: do not fail when only ipv6 addr is specified"

- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/network-functions
The commit cd475bf315b9c08e9f1732c0b9de95729025d1c5 introduced a regression where dhclient is now sending the current hostname (the `-H` option) everytime when `ifup-eth` is used.
This can cause a problem in case the hostname is not specified in `/etc/sysconfig/network` or `/etc/sysconfig/network-scripts/ifcfg-eth*`, where the dhclient would eventually send `localhost` as current hostname, which is obviously wrong.
This PR tries to fix this issue by checking if the hostname is set or not.
Originally reported in [RHBZ #1350602](https://bugzilla.redhat.com/show_bug.cgi?id=1350602).
I'm not sure how `dhclient` behaves in case no hostname is specified, so the review of this commit is especially needed.
> network-functions: do not send hostname via dhclient everytime

- src/ipcalc.c
Backport of commit ee0eb388018636443799a9fa88eee47c86ab1565 into RHEL-6.9. Resolves [RHBZ #1377986](https://bugzilla.redhat.com/show_bug.cgi?id=1377986).
> ipcalc: detect invalid mask

- sysconfig/network-scripts/ifdown-ipv6
Typo introduced in commit 432951d.
Related: https://github.com/fedora-sysv/initscripts/pull/2
Signed-off-by: Pavel Šimerda <pavlix@pavlix.net>
> fix typo in IPV6_SET_SYSCTLS

- rc.d/init.d/network
This is backport of commit 82c97b4ac121269ecb829 to RHEL-6 branch. Resolves [RHBZ #1315018](https://bugzilla.redhat.com/show_bug.cgi?id=1315018).
> network: Treat other tunnel interfaces, fixes ifdown stage

- init/kexec-disable.conf
Previously, the kexec memory was freed everytime. After patch from [RHBZ #734987](https://bugzilla.redhat.com/show_bug.cgi?id=734987),
it does not free the kexec memory at all.
This patch fixes this regression (resolves [RHBZ #1378198](https://bugzilla.redhat.com/show_bug.cgi?id=1378198)).
> init/kexec-disable.conf: release kexec memory properly

- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/network-functions
Previously, some administrators were unable to force initscripts to *NOT* obtain hostname from DHCP, even though they were using static configuration of network. Righ now, setting  `NO_DHCP_HOSTNAME` to `yes`, `true` or `1` in `/etc/sysconfig/network` will allow them to do so.
> sysconfig/network: NO_DHCP_HOSTNAME option introduced

- sysconfig/network-scripts/network-functions-ipv6
Instead of adding the IPv6 address when ifup is called, we replace the address, because it might have been auto-assigned before by RA.
This is to assure that static NIC configuration will take effect if the NIC was already dynamically configured by RA.
> ipv6_add_addr_on_device: replace the existing address on NIC

- sysconfig/network-scripts/ifup-eth
When backporting commit ca3cea691b6be245e43740a8358ecc47add5684f into RHEL6, I have accidentally introduced a regression - the `${LEASEFILE}` variable was not specified, thus causing the system to not receive an assigned IP address from DHCP.
This resulted in RHEL6 being booted without network connectivity. This pull-request relates to [RHBZ #1350602](#1350602).
> Fix regression in commit ca3cea691b6 - ${LEASEFILE} not specified

- sysconfig/network-scripts/ifup-eth
With quote marks all the parameters to dhclient are passed as one
Resolves: #1410429
> ifup-eth: remove quote marks

- initscripts.spec
Rebase to fix the latest regression (in https://github.com/fedora-sysv/initscripts/commit/ca3cea691b6be245e43740a8358ecc47add5684f#diff-1f650863fcc0e18c616793dca777ef28R323) found.
> [RHEL6] Rebase to 9.03.57

- sysconfig/network-scripts/ifup-aliases
It looks that during backport $() was replaced with ""
Resolves: [RHBZ #1413976](https://bugzilla.redhat.com/show_bug.cgi?id=1413976)
> ifup-aliases: we want to call the arping

- sysconfig/network-scripts/ifup-eth
I have accidentally brought back the regression in [BZ #1410429](https://bugzilla.redhat.com/show_bug.cgi?id=1410429). This commit fixes the issue.
> [RHEL-7] ifup-eth: remove quote marks

- rc.d/init.d/network
This is a regression caused by a2ecd685d60fd013b121e78aebd5558121f4fb5e
Resolves: rhbz#1436061
> init.d/network: start vpninterfaces

- sysconfig/network-scripts/ifdown-eth
But it is stuck some time. This is a forward-patch from RHEL6, to allow using
`ifdown` on `loopback` device.
> ifdown-eth: we need to flush global scope as well

- rc.d/init.d/functions
Taken from RHEL-6.9, for forward compatibility.
> killproc/status: add missing '-b <binary>' option

- initscripts.spec
Marking these files with `%config(noreplace)` will make sure we do not override them for sysadmins when we release new update.
> specfile: mark 'rwtab' and 'statetab' as config files

- systemd/rhel-autorelabel
This should prevent boot loops when 'touch /.autorelabel' has been used. For more info, see [RHBZ #1385272](https://bugzilla.redhat.com/show_bug.cgi?id=1385272).
> [RHEL-7] rhel-autorelabel: synchronize cached writes before reboot

- sysconfig/network-scripts/network-functions
- systemd/fedora-readonly
Previously, the network scripts were using `$HOSTNAME` from `sysconfig/network` configuration, but this has been obsoleted, and the functionality has not been updated properly yet. This commit fixes the issue.
> re-add missing $HOSTNAME initialization

- examples/networking/ifcfg-eth-dhcp
- sysconfig.txt
- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/network-functions
The `DHCP_FQDN` is similar to `DHCP_HOSTNAME` option, but it expects the fully qualified domain name to be used there.
In case both `DHCP_HOSTNAME` and `DHCP_FQDN` are set, then the `DHCP_FQDN` will used (*and warning will be produced*). This is the same behaviour as *NetworkManager* does it.
> ifup-eth: introduce DHCP_FQDN option

- src/usleep.c
For F26 and F27 we will print deprecation warning, trying to move people to use
sleep instead. In F28 the usleep will be completely dropped, hopefully.
This is the initial step to resolve the issue #68.
> usleep: print deprecation warning from now on

- rc.d/init.d/functions
- src/usleep.1
- sysconfig/network-scripts/ifdown-eth
- sysconfig/network-scripts/network-functions
Also, add the deprecation warning into manual page of `usleep(1)`.
> Replace usleep(1) calls with sleep(1) calls

- rc.d/init.d/functions
- src/rename_device.c
Turned out in [BZ #1455419](https://bugzilla.redhat.com/show_bug.cgi?id=1455419) that we are not ignoring `*.olg` files, even if we [should](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Network_Configuration_Using_sysconfig_Files.html).
> Add *.old to list of ignored files

- sysconfig.txt
- sysconfig/network-scripts/ifup-aliases
- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/network-functions
By setting the `ARPUPDATE` to 'no', administrator can disable updating neighbouring computers with ARP information about current NIC. This is especially needed when using *LVS Load Balancing with Direct Routing* enabled.
The `ARPUPDATE` defaults to `yes`.
> Introduction of ARPUPDATE option

- sysconfig.txt
- sysconfig/network-scripts/ifup-aliases
- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/network-functions
The `ARPUPDATE` option has been introduced. It defaults to 'yes'.
By setting the `ARPUPDATE` to `no`, administrator can disable updating neighbouring computers with ARP information about current NIC. This is especially needed when using LVS Load Balancing with Direct routing enabled.
Resolves: [RHBZ #1440888](https://bugzilla.redhat.com/show_bug.cgi?id=1440888)
> [RHEL6] Fix for LVS with Direct Routing

- Makefile
- initscripts.spec
- sysconfig.txt
- sysctl.conf
This file now only contains lines to disable netfilter on bridges. In kernel 3.18 this filtering functionality was made non-default by moving it to br_netfilter [BZ #512206](https://bugzilla.redhat.com/show_bug.cgi?id=512206). Anybody who actually wants to use `br_netfilter` has to load it explicitly anyway, so disabling it through sysctl isn't necessary anymore.
The reason for removal is that by default (i.e. when `br_netfilter` is not loaded), we get a warning on every boot (*which is confusing for users and inelegant*):
``` log
systemd-sysctl[210]: Couldn't write '0' to 'net/bridge/bridge-nf-call-ip6tables', ignoring: No such file or directory
systemd-sysctl[210]: Couldn't write '0' to 'net/bridge/bridge-nf-call-iptables', ignoring: No such file or directory
systemd-sysctl[210]: …
```
> Drop sysctl.d/00-system.conf

- Makefile
- initscripts.tmpfiles.d
- rc.d/init.d/functions
- src/netreport.c
- sysconfig.txt
- sysconfig/network-scripts/ifdown-bnep
- sysconfig/network-scripts/ifdown-eth
- sysconfig/network-scripts/ifdown-ippp
- sysconfig/network-scripts/ifdown-ipv6
- sysconfig/network-scripts/ifup-bnep
- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/ifup-ipv6
- sysconfig/network-scripts/network-functions
- sysconfig/network-scripts/network-functions-ipv6
A small cleanup, I hope there's no functional change, except when for whatever reason /var is not mounted and the /var/run → /run symlink is missing.
> Replace references to /var/run with /run

- rc.d/init.d/functions
- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/network-functions
This pull-request contains 2 commits. First introduces an auxiliary function for converting values of time units smaller than 1 second into seconds. The second fixes an issue when bridge can't obtain IP from DHCP right after system start, because `ifup-eth` does not wait for STP to complete its starup ([RHBZ #1380496](https://bugzilla.redhat.com/show_bug.cgi?id=1380496)).
The second commit is based on patch from Richard Alloway (@N3WWN).
> [Bridge] Wait for STP to complete setup

- Makefile
This will avoid `/` duplicating at the path beginning, and should make the patch from @keszybz finally work. :)
> Makefile: $ROOT variable is now empty by default

- initscripts.spec
This was caused by commit 13d638c0a7df4a.
> specfile: Fix failing build for s390* architecture

- src/usleep.c
Also drop the argv[0] as previx — the message already includes the
name of the program.
$ ./src/usleep 300
warning: usleep is deprecated, and will be removed in near future!
warning: use "sleep 0.3" instead...
%g will print a normal decimal point for all values that are likely to
be used (the smallest one possible is 1/1000 = 0.001). For very large
values scientific notation will be used, which is not very pretty, but
sleep accepts that, so there's no issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1494168
> usleep: change the error message to print the full replacement commadline

- sysconfig.txt
- sysconfig/network-scripts/ifup-aliases
- sysconfig/network-scripts/ifup-eth
- sysconfig/network-scripts/network-functions
This is the backport of already included patch in Fedora and RHEL6, into RHEL7:
`The ARPUPDATE option has been introduced. It defaults to 'yes'.`
> By setting the ARPUPDATE to 'no', administrator can disable updating neighbouring computers with ARP information about current NIC. This is especially needed when using LVS Load Balancing with Direct routing enabled.
> [RHEL7] ARPUPDATE introduced

- Makefile
- initscripts.spec
- systemd/system/fedora-domainname.service
- systemd/system/fedora-import-state.service
- systemd/system/fedora-loadmodules.service
- systemd/system/fedora-readonly.service
These symlinks are no longer needed, because services enabled by default are now managed by `fedora-release` package.
Before merging this PR/releasing new version of initscripts, we should wait for necessary changes to be made in `fedora-release`.
> Remove symlinks for fedora-* services

- Makefile
This is useful for RHEL-7 as well.
> [RHEL7] Reintroduce 'make archive' for testing purposes

- Makefile
- initscripts.spec
- systemd/system/rhel-autorelabel-mark.service
- systemd/system/rhel-autorelabel.service
- systemd/system/rhel-configure.service
- systemd/system/rhel-domainname.service
- systemd/system/rhel-import-state.service
- systemd/system/rhel-loadmodules.service
- systemd/system/rhel-readonly.service
These symlinks are no longer needed, because services enabled by default are now managed by `redhat-release` package.
Before merging this PR/releasing new version of initscripts, we should wait for necessary changes to be made in `redhat-release`.]
This PR fixes [BZ #1395391](https://bugzilla.redhat.com/show_bug.cgi?id=1395391) and [BZ #1357648](https://bugzilla.redhat.com/show_bug.cgi?id=1357648).
> [RHEL7] Remove symlinks for initscripts' services

- sysconfig/network-scripts/ifdown-post
- sysconfig/network-scripts/ifup-post
- sysconfig/network-scripts/network-functions
This is complete rework of how we generate the `/etc/resolv.conf`.
* always update `nameserver` & `search` entries when `DNS*` and `DOMAIN` entries (respectively) were updated in `ifcfg-*` files
* always update the order of `nameserver` entries when the order of `DNS*` options was updated
* always keep `/etc/resolv.conf.save` as a proper backup - do not overwrite it everytime when updating `nameserver` or `search`
* added support for `DNS3` option, since this is what *GLIBC* currently suppports
* added logic to be able to process duplicate `DNS*` options
* added logic to be able to process randomly omitted `DNS*` options
(e.g. omitting `DNS1` while specifying `DNS2` and/or `DNS3` will still work now)
This work is based on these two RHEL-7.5 BZs: [RHBZ …
> [ifup-post] Always update nameserver & search entries in /etc/resolv.conf

- sysconfig/network-scripts/ifdown-post
- sysconfig/network-scripts/ifup-post
- sysconfig/network-scripts/network-functions
This is the same pull-request as #131, backported to RHEL-7, but it does not contain the fixes for backing up the `/etc/resolv.conf` file.
> [RHEL7] ifup-post: always update nameserver & search entries in /etc/resolv.conf

- initscripts.spec
IMHO, we can't just drop the `Requires:` on `redhat-release` now, it could be dangerous. Instead we're just updating it and adding `Conflicts:` to make sure users can't install newer initscripts with older `redhat-release`. It would most likely end up with unbootable system.
> [RHEL7] Require 'redhat-release' and add conflict with older version

- initscripts.spec
This way the `fedora-release` will be still installed by default together with initscripts, but initscripts will no longer block users from unistalling `fedora-release`, if they require so.
IOW, the Fedora branding will not be forced by initscripts any more.
> [specfile] drop dependency on /etc/system-release completely

- initscripts.spec
New release for Fedora 27 (as part of 0-day updates) and Fedora Rawhide (F28).
> [Release] 9.78

- rc.d/init.d/network
- sysconfig.txt
On machines that use systemd as PID1 but don't enable pam_systemd, SSH sessions aren't terminated properly on shutdown (see https://bugzilla.redhat.com/show_bug.cgi?id=1047614 for details). This PR adds a knob to workaround the issue, by optionally leaving the network up during shutdown. This is only implemented for systemd hosts, but it could be extended to SysV ones as well if desired.
> network: add knob to optionally keep interfaces up during shutdown

- sysconfig/network-scripts/ifdown-post
Empty `${RESOLV_MODS}` was causing a deletion of config files in `/etc/ppp/peers/`.
Resolves: #155
> ifdown-post: fix logical error in commit 5d61564

- initscripts.spec
To fix the regression reported in \#155 in Fedora 27 and Rawhide.
> [Release] 9.79

- rc.d/init.d/functions
Cherry-picking for RHEL-7 to avoid regression when doing upgrade.
More info: https://bugzilla.redhat.com/show_bug.cgi?id=1518429
> [RHEL7] init.d/functions: fix sourcing for ksh

- rc.d/init.d/functions
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1518429
> [RHEL6] init.d/functions: fix sourcing for ksh

- systemd/system/rhel-readonly.service
https://bugzilla.redhat.com/show_bug.cgi?id=1553093
> rhel-readonly.service: target name for random seed fixed

- sysconfig.txt
- sysconfig/network-scripts/ifup-tunnel
This is a newish feature upstream. You can now set the external flag on a
ip6_tunnel type interface (though not the primary one, ip6tnl0), and doing so
will allow it to decapsulate any packet, and assuming that the inner address is
the one on that interface, it'll drop it back on the stack.
This is useful for DSR vips. While v6-in-v6 was already supported, this allows
v4-in-v6 which is necessary to serve v4 traffic in a v6only infrastructure.
There's comments in ifup-tunnel that imply it was designed only for GRE tunnels,
but this still seems like the best place for this.
> ifup-tunnel: Support 'external' tunnels

- initscripts.spec
- rc.d/init.d/functions
More info: https://bugzilla.redhat.com/show_bug.cgi?id=1571035
> RHEL-6 | cryptsetup: do not forward STDERR to /dev/null when promting for passphrase

- rc.d/init.d/netconsole
Since we are using systemd, the Default-Start/Stop keywords were omitted. Basically the LSB header is quite similar to LSB header of network service...
> netconsole: LSB header added

- sysconfig/network-scripts/ifdown-eth
Previously, there were 2 additional conditions related to this part of code, but they were removed in time, so this last condition has remained an artifact and is de-facto obsolete.
However, the 'pidof -x dhclient' condition could cause the network service to hang on stop/restart when processes were executed from a network share... Removing that condition should hypothetically fix it.
> ifdown-eth: no longer needed 'pidof -x dhclient' condition removed

- sysconfig/network-scripts/network-functions
Instead of displaying messages without context, like this:
```
./network-functions: line 571: echo: write error: Invalid argument
./network-functions: line 598: echo: write error: Permission denied
```
We will now display pretty error messages (via `net_log`) about what has actually failed...
> network-functions: add error messages for bonding installation

- sysconfig/network-scripts/network-functions
network-functions uses awk to tranform the mac address to upper case.
Replace awk with tr which is two order of magnitude faster:
$ time awk '{ print toupper($0) }' </usr/share/dict/words >/dev/null
real    0m0,227s
user    0m0,224s
sys     0m0,004s
$ time tr '[a-z]' '[A-Z]' </usr/share/dict/words >/dev/null
real    0m0,005s
user    0m0,000s
sys     0m0,005s
Also use here-strings instead of spawning a subshell and a pipe.
Signed-off-by: Matteo Croce <mcroce@redhat.com>
> network-functions: use tr to upper case strings rather than awk

- initscripts.spec
See https://bugzilla.redhat.com/show_bug.cgi?id=1512688 for more info.
NOTE: We shouldn't merge this commit until F28 is released as GA - to make sure the upgrades go smoothly... :)
> specfile: remove the systemctl call in the %postun phase

- service
- sys-unconfig
- sysconfig/network-scripts/ifdown-sit
- sysconfig/network-scripts/ifup-ipv6
- sysconfig/network-scripts/init.ipv6-global
$" is a BASH extension to translate text.
Replace the shebang with /bin/bash to avoid parsing errors,
as even BASH has a POSIX compliant mode when run as sh.
Signed-off-by: Matteo Croce <mcroce@redhat.com>
> use proper shebang

- rc.d/init.d/network
More info: https://bugzilla.redhat.com/show_bug.cgi?id=1554690
> RHEL-7 | network.service: 'reload' removed

- sysctl.conf.s390
They have sane default values in kernel for IBM machines as well:
https://bugzilla.redhat.com/show_bug.cgi?id=1493069
> RHEL-7 | sysctl.conf.s390: drop SHMALL and SHMMAX

- sysconfig/network-scripts/network-functions
Same as #183. This has been requested by our customer:
https://bugzilla.redhat.com/show_bug.cgi?id=1542514
> RHEL-7 | network-functions: add error messages for bonding installation

- sysconfig/readonly-root
Without appending the `ro` to mount options of `/` mount point the system will be still mounted as read-write, even when `READONLY=yes`.
> sysconfig/readonly-root: Clarify the usage of readonly-root.

- sysconfig/readonly-root
Same problem as in #189. More info: https://bugzilla.redhat.com/show_bug.cgi?id=1444018
> RHEL-7 | sysconfig/readonly-root: Clarify the usage of readonly-root.

- systemd/rhel-autorelabel
In some circumstances the system could be started into UEFI shell instead of RHEL after the rhel-autorelabel has run... This commit should fix this behaviour.
> RHEL-7 | rhel-autorelabel: set UEFI BootNext == BootCurrent

- systemd/fedora-readonly
Due to some change in bash-4.4, it started to give out warnings about ignored null-byte characters in the command substitution:
https://bugzilla.redhat.com/show_bug.cgi?id=1472137#c2
> fedora-readonly: command substitution warning fixed (null-byte input)

- initscripts.spec
- rc.d/init.d/network
- sysconfig.txt
Backport of this change to RHEL-7 as well. This option is not used by default.
* network: add knob to optionally keep interfaces up during shutdown
> [RHEL-7] network: add knob to optionally keep interfaces up during shutdown

- initscripts.spec
The leftover `%{_isa}` was causing the Koji build to fail:
https://koji.fedoraproject.org/koji/taskinfo?taskID=27631523
> specfile: fix failing build because of incorrect use of %{_isa}

- Makefile
- initscripts.spec
This will allow services to install drop-in files into these folders for the 'readonly-root' service, but that service won't have to be installed by default as a result...
NOTE: We have to wait until the https://pagure.io/filesystem/pull-request/1 is merged, before we can merge the change in initscripts.
> Move the /etc/rwtab.d & /etc/statetab.d folders to 'filesystem'

- sysconfig/network-scripts/ifdown-eth
This is backport to RHEL-7.
> Previously, there were 2 additional conditions related to this part of code, but they were removed in time, so this last condition has remained an artifact and is de-facto obsolete.
>
> However, the 'pidof -x dhclient' condition could cause the network service to hang on stop/restart when processes were executed from a network share... Removing that condition should hypothetically fix it.
> [RHEL-7] ifdown-eth: no longer needed 'pidof -x dhclient' condition removed

- rc.d/init.d/netconsole
Backport to RHEL-7.
>  Since we are using systemd, the Default-Start/Stop keywords were omitted. Basically the LSB header is quite similar to LSB header of network service...
> [RHEL-7] netconsole: LSB header added

- rc.d/init.d/network
This is backport to RHEL-7:
> This partially reverts the commit 15eaf7ece, because systemd's generated unit files might have incorrect dependencies at some circumstances, thus causing diskless nfs-clients to hang while unmounting root filesystem after '$ service network stop'.
> [RHEL-7] network: parsing of /proc/mounts returned

- initscripts.spec
- network-scripts/ifup-eth
Because the return value of `convert2sec()` function can sometimes be decimal, the follow up `expr` call can fail, since `expr` does not support floating point calculations. This can sometimes lead to error:
```shell
expr: non-integer argument
/etc/sysconfig/network-scripts/ifup-eth: line 91: [: 0: unary operator expected
```
To solve this bug, we switch to `bc` utility, which supports floating point computations. Using `bc` should also be much faster than calling `gawk` to do this.
Resolves: #227
> ifup-eth: use 'bc' instead of 'expr' when computing $forward_delay

- etc/rc.d/init.d/network
- network-scripts/ifdown
- network-scripts/ifup
In case of 'network' service these warnings are displayed only once, to not spam unnecessarily user's journalctl if they have many NICs.
> [RHEL8] network/ifup/ifdown: deprecation warnings for 'network-scripts' added

- etc/rc.d/init.d/network
- network-scripts/ifdown
- network-scripts/ifup
- src/consoletype.c
- src/genhostid.c
- src/usleep.c
We need to allow disabling of deprecation messages for RHEL-8 for obvious reasons.
> [RHEL-8] Allow disabling of deprecation warnings

- Makefile
This PR will change the message created for future tags, and tag won't be automatically be created when issuing `make release-commit`.
> [Makefile] fixes for 'release-commit' and 'tag'

- network-scripts/ifup-post
Before the commit 5d6156454bf8 we were not updating the `/etc/resolv.conf` file if the `RESOLV_MODS` was empty...
**BEFORE (correct behaviour):**
```bash
if ! is_false "$PEERDNS" || [ -n "$RESOLV_MODS" ] && ! is_false "$RESOLV_MODS"; then
```
**NOW (bad behaviour):**
```bash
if ! is_false "${PEERDNS}" || ! is_false "${RESOLV_MODS}"; then
```
This is causing the `/etc/resolv.conf` file to be always updated when `RESOLV_MODS` is not set... By using `is_true "${RESOLV_MODS}"` we achieve the same behaviour as before (correct).
See https://bugzilla.redhat.com/show_bug.cgi?id=1610411 for more info.
> ifup-post: fix incorrect condition for RESOLV_MODS

- network-scripts/ifup-eth
IPv6 dhclient daemon only tries one time to obtain a IPv6 address
from a DHCPv6 server regardless of the setting of PERSISTENT_DHCLIENT.
PERSISTENT_DHCLIENT option is only used for IPv4 dhclient daemon.
With the popularization of IPv6 protocol, some users prefer setting
IPv6 like IPv4. I think there are two solutions as follows,
1. adopt PERSISTENT_DHCLIENT option to both IPv4 and IPv6.
2. create a new option, such as PERSISTENT_DHCLIENT_IPV6 option,
just for IPv6.
The first solution does not introduce addition options, and the IPv4
and IPv6 settings are consistent. So I perfer choosing the first
solution.
Fixes: bf00a0048 ("Replace /var/run with /run everywhere")
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>
> ifup-eth: apply PERSISTENT_DHCLIENT to IPv6 dhclient daemon

- doc/sysconfig.txt
- etc/rc.d/init.d/functions
Now with systemd, this does not work pretty well and users really should
use systemd unit-files for this.
> rc.d/functions: remove support cgroups

- network-scripts/ifdown
- network-scripts/ifup
In ifup/ifdown scripts, move deprecation waring info after
source_config, so users can config DEPRECATION_WARNING_ISSUED in
ifcfg-** file to decide whether show deprecation waring info when
calling ifup/ifdown.
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>
> ifup/ifdown: print DEPRECATION_WARNING_ISSUED waring info after source_config

- Makefile
Sed command get version number from spec file and increment last
number by one. Work like old awk command was intended to work.
Source: https://stackoverflow.com/questions/14348432/how-to-find-replace-and-increment-a-matched-number-with-sed-awk/14348899
> Replace not working awk command with sed

- etc/rc.d/init.d/functions
Fix issue when functions provided by ``/etc/rc.d/functions`` is used, escape sequence is output under systemd service units and logged into ``/var/log/messages``.
This is a regression issue caused by the commit f88dbd98e992 where
consoletype command was dropped.
Resolves: [https://bugzilla.redhat.com/show_bug.cgi?id=1738436](url)
> rc.d/functions: fix escape sequence being output under systemd service units

- sysconfig.txt
- sysconfig/network-scripts/ifup-tunnel
- sysconfig/network-scripts/network-functions
Add option for IPv6 GRE tunnel.
Resolve: [https://bugzilla.redhat.com/show_bug.cgi?id=1691552](url)
> Add ip6gre tunnel option - rhel7

- network-scripts/ifup-eth
Fixes https://bugzilla.redhat.com/1743522
An uninitialized variable was copied from a closed PR [1]
to submitted PR [2].
[1] https://github.com/fedora-sysv/initscripts/pull/212
[2] https://github.com/fedora-sysv/initscripts/pull/213
Signed-off-by: Bell Levin <blevin@redhat.com>
> ifup-eth: Fix bridge setting stp option

- network-scripts/ifup-eth
Fixes https://bugzilla.redhat.com/1743522
An uninitialized variable was copied from a closed PR [1]
to submitted PR [2].
[1] https://github.com/fedora-sysv/initscripts/pull/212
[2] https://github.com/fedora-sysv/initscripts/pull/213
Signed-off-by: Bell Levin <blevin@redhat.com>
(cherry picked from commit dd703a8494647d401dbffa0f036233e08044ec60)
> [RHEL8] ifup-eth: Fix bridge setting stp option

- Makefile
- initscripts.spec
File rc.local is owned by systemd, so initscripts should not touch it any more.
> rc.local: Initscripts no longer care about rc.local

- Makefile
- initscripts.spec
File rc.local is owned by systemd, so initscripts should not touch it any more.
> rc.local: Initscripts no longer care about rc.local 

- sysconfig/network-scripts/network-functions-ipv6
Check both scopes for tentative addresses and wait for them.
Resolves: #1773798
> Wait for scope link addresses as well as for scope global addresses

- network-scripts/network-functions-ipv6
Fix issue when interface has assigned only local address in tentative state and DHCPv6 isn't able to assign address to that interface. With this patch network-scripts will wait until tentative state is gone (wait for DAD) for all scopes including local one.
Resolves: #1809601
>  Wait for scope link addresses as well as for scope global addresses

- rwtab
Chrony isn't able to write into its files while stateless mode is
active. This patch should avoid this issue.
Resolves: #1838260
> rwtab: Add support for chrony

- etc/rc.d/init.d/network
Option -L is not supported in grep 3.2+
Related to #rhbz1824324
-----------
Sugested by @lnykryn
Related to issue #300
(cherry picked from commit 04bb81ecfef80477a6bfa5b7598f27f5ad53f86e)
> Replace grep -EL with subshell since -L changed behaviour

- initscripts.spec
- network-scripts/ifup-eth
backport of: 0be5319
Resolves:    #1826637
> ifup-eth: Switch to bc utility, which supports floating point computations. - RHEL8

- network-scripts/ifup
- network-scripts/ifup-eth
Fix the problem when the device name could be interpreted as an iproute2 keyword. For example, for a bridge slave named "a" the iproute2 would treat the name as a prefix of keyword "address" and the network-scripts would fail to set the bridge master.
Related: rhbz #1859785
> Add optional 'dev' keyword

- etc/rc.d/init.d/functions
Some versions of grep (like busybox's) do not support --quiet.
So use -q instead like in the rest of the file.
Signed-off-by: Chaitanya Vadrevu <chaitanya.vadrevu@ni.com>
> rc.d/functions: replace grep's --quiet with -q

- etc/rwtab
Fixes issue when updatedb does not have the ability to update the mlocate.db
> Allow updating mlocate.db while in readonly root mode

- etc/rwtab
Adding rfkill switch status into rwtab.
> Allow updating rfkill switch status while in readonly root mode

- network-scripts/ifup
- network-scripts/ifup-ippp
Use internal network-scripts function ``net_log()`` instead of
``/usr/bin/logger`` if possible to make code more consistent and cleaner.
> network-scripts: Use net_log() instead of logger

- Makefile
- initscripts.spec
Start using legacy date-stamp to remain consistent changelog
> makefile: Use rpmdev-bumpspec's legacy date option

- network-scripts/ifup
- network-scripts/ifup-ctc
- network-scripts/ifup-eth
- network-scripts/ifup-ippp
- network-scripts/ifup-plip
- network-scripts/ifup-plusb
- network-scripts/ifup-tunnel
- network-scripts/network-functions
- network-scripts/network-functions-ipv6
Some interfaces like Open vSwitch bridges using the userspace datapath,
needs the link to be kept down to avoid issues.
Add a LINKSTATUS=[down|up] ifcfg parameter to add this functionality.
If not specified, the link will default to up as before.
Patch provided by Matteo Croce <mcroce@redhat.com>
> network: add option to keep the link down

- src/rename_device.c
if rename_device is killed during fopen period in take_lock ,LOCKFILE will not be remove in sighandler.
Excute rename_device again,  LOCKFILE  is exist ,but the process with pid in LOCKFILE  is not running, take_lock will never return.
> remove rename_device_lock when process does not exist

- src/rename_device.c
Reverts fedora-sysv/initscripts#359
> Revert "remove rename_device_lock when process does not exist"

- initscripts.spec
Add BuildRequires: make
https://fedoraproject.org/wiki/Changes/Remove_make_from_BuildRoot
> spec: sync with Fedora

- doc/sysconfig.txt
- network-scripts/ifup-aliases
- network-scripts/ifup-eth
Introduced in the bonding driver (commit ae46f184bc1f) Driver now reports transmission failures.
Before that, it silently dropped the packet and replied with success error code.
The arping of iputils retries endlessly when a transmission error occurs.
This patch fix this behavior.
>  network scripts: Avoid infinite loop of arping

- etc/rc.d/init.d/functions
- initscripts.spec
- usr/sbin/service
This changes moves service script into `initscripts-service` subpackage. The subpackage
could be install without main package.
This change allows `audit` not to require `initscripts` and require only `initscripts-service` instead.
Requested by: msekleta@redhat.com
> spec: Move service script into subpackage

- initscripts.spec
As a easy way to get full legacy system V support.
> spec: Initscripts now requires chkconfig

- initscripts.spec
The network-scripts package is legacy and deprecated, so nobody should depend on this!
If ifcfg-style configuration is still desired, NetworkManager can do this.
Thus, mark this as deprecated to ensure people know to not depend on it.
Reference: https://docs.fedoraproject.org/en-US/packaging-guidelines/deprecating-packages/
> spec: Mark network-scripts as deprecated

- Makefile
Sed command get version number from spec file and increment last
number by one. Work like old awk command was intended to work.
Source: https://stackoverflow.com/questions/14348432/how-to-find-replace-and-increment-a-matched-number-with-sed-awk/14348899
(cherry picked from commit bfda3cc2acdea827909e6c89bda5bbb5140cda6c)
> spec: Replace not working awk command with sed

- etc/rc.d/init.d/functions
- network-scripts/ifup-eth
- network-scripts/network-functions
#396 
In some embedded environments, instead of using GNU Bash for size reasons, the Ash (shell provided by busybox) is used. But init.d/network and init.d/functions are not very well adapted for Ash. Here are the two problems I found:
1) Use killproc to kill the given service process
Steps:
```
#!/bin/bash
. /etc/init.d/functions
test()
{
sleep 30 &
killproc sleep
}
test
```
run this testcase returns an error, and sleep is not killed:
This is because Ash cannot use "+=" for string concatenation.
2) I found out that here string(<<<) and c-style for-loop( for (( ; ; )) ) are
used in network-scripts. But Ash doesn't support them either. So when I run:
"/etc/rc.d/init.d/network status" gives these errors:
```
```
The last two patches are used to fix this problem.
The problems mentioned above …
> Make the init.d/network and init.d/functions available on Busybox's shell

- network-scripts/ifup-routes
This should resolve the scenario when the link is brought up prior to disabling `accept_ra`.
This only happens when both IPv4 and IPv6 address is on the interface, because network-scripts does IPv4 first and brings up the interface.
Then it does IPv6 which disables the RA's, at that point the node has already learned the route from RA and setting a default route fails.
Using `ip route replace` we ensure if the above scenario happens we end-up with the correct default ipv6 route.
Huge thanks to @hjensas who debugged this issue and prepared a patch!
Related: [`#2034799`](https://bugzilla.redhat.com/show_bug.cgi?id=2034799)
> ifup-routes: Use `ip route repace` to avoid race

- network-scripts/ifup-routes
This should resolve the scenario when the link is brought
up prior to disabling accept_ra.
This only happens when both IPv4 and IPv6 address is on
the interface, because network-scripts does IPv4 first
and brings up the interface.
Then it does IPv6 which disables the RA's, at that point
the node has already learned the route from RA and setting
a default route fails.
Using `ip route replace` we ensure if the above scenario
happens we end-up with the correct default ipv6 route.
Huge thanks to Harald who debugged this issue and prepared a patch!
Resolves: #2040679
>  ifup-routes: Use ip route repace to avoid race

- network-scripts/ifup-routes
Since other types might fail due to `replace` to be undefined.
Related: #2034799
> ifup-routes: Use `ip replace` only on type `route`

- network-scripts/ifup-routes
Since other types might fail due to `replace` to be undefined.
Also revert quotes...
>  ifup-routes: Use `ip replace` only on type `route`

- initscripts.spec
How to reproduce:
```sh
(. /etc/sysconfig/network-scripts/network-functions; is_nm_running && echo "yes")
```
Resolves: #1832897
Co-authored-by: Till Maas <opensource@till.name>
> spec: network-scripts needs to depend on dbus-tools for NetworkManager detection

- initscripts.spec
It allows to `rename_device` to be installed independently on `initscripts`.
> spec: Move `rename_device` to subpackage `initscripts-rename-device`

- initscripts.spec
Since initscripts requires these packages anyway, the obsoletes
aren't necessary. They're only useful if you split off a new
subpackage and *don't* have the main package require it, but
you still want it to be installed on updates. In this case,
initscripts requires both initscripts-rename-device and
initscripts-service, so there's no need for them to obsolete
older versions of it.
The initscripts-rename-device obsoletes was somehow messing up
live image creation during the openQA update test (caused the
live image not to include initscripts at all). This fixes that.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
(cherry picked from commit 4e39c08825a55107a6accf7ad7b4d82ddd30e9ec)
> spec: Drop unnecessary obsoletes

- initscripts.spec
It allows to rename_device to be installed independently on initscripts.
(cherry picked from commit https://github.com/fedora-sysv/initscripts/commit/69a2526fa919a1ab215a4b19640b2214e0a1d78e)
Resolves: #2057917
> (#2057917) spec: Move rename_device to subpackage initscripts-rename-device

- usr/sbin/service
Symlink `/etc/init.d -> rc.d/init.d` is provided by initscripts package.
> service: Exit when `/etc/init.d` is missing

- usr/libexec/readonly-root
Noticed that paths with spaces in `/etc/statetab` and `/etc/statetab.d/*` weren't interpreted.
Since a for loop was used, bash just splitted paths at default IFS chars.
Since we could have paths with spaces like `/opt/my service` in statetab, we need to read the statetab files line per line, with IFS being '\n', which can be accomplished by using a while loop.
This is already done for rwtab.
> Fix splitting spaces in paths from statetab files

- Makefile
- initscripts.spec
`network-scripts` have been deprecated for a long time. It's time to drop them from Fedora.
Everybody should use `NetworkManager` or `systemd-networkd` instead.
Resolves: #2262795
> fedora: don't build network-scripts rpm in f40+

- network-scripts/ifup-routes
When static routes are added via route-<interface> file, the ifup-routes script will skip adding routes if entries not starting with ADDRESS0.
Good to print a warning so that users are aware of this.
> ifup-routes: print warning when ADDRESS0 entry is missing

- initscripts.spec
This commit partially reverts commit b751727763197b6d54735622274f644242141326 and e35db934845b01173280c1d05a9aa1d294f2627c
Resolves: [#2274830](https://bugzilla.redhat.com/show_bug.cgi?id=2274830)
> fix: return support for network-scripts for Fedora 40

- initscripts.spec
Preparation for https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin. The glob in %files wase causing a warning about duplicate entries in %files.
> Fix build when %_bindir==%_sbindir

- initscripts.spec
This reverts commit 4ef61c61d60b6bd337504b6898b0fa7bce8afbc9.
Fedora 41 Change Proposal: https://fedoraproject.org/wiki/Changes/NetworkScriptsRemoval
> Remove support for network-scripts for Fedora 41+

- network-scripts/network-functions
Currently the "^" anchor is applied to the "connected" case and does not apply to the "connecting" case in the grep due to the way the brackets () are placed. This can cause the grep statement to incorrectly return a match.
For ex: When trying to check for eth0 using is_nm_handling(), "bondeth0:connecting" would also match the grep and return incorrectly.
> network-functions: Fix a bug in is_nm_handling()

- network-scripts/ifup-eth
retry arping one more time in ifup-eth when sendto failed
> retry arping one more time in ifup-eth when sendto failed
