fedora-sysv/initscripts

rc.d/init.d/network
Fix style to be consistent with the one discussed in #3. No functional changes, git diff -w shows no changes as well.
=> network: remove tabs and fix spacing

sysconfig/network-scripts/ifup-aliases, sysconfig/network-scripts/ifup-eth
forward-port a patch from rhel6 branch
=> ifup-eth: if arping fails, output responding MAC

sysconfig/network-scripts/network-functions-ipv6
This pull request relates to RHBZ [#1378917](https://bugzilla.redhat.com/show_bug.cgi?id=1378917).
=> ipv6_wait_tentative(): exit immediately when dadfailed occurs

initscripts.spec
Lets call this release-candiate number 1... :)
=> [RHEL-6.9] Rebase to 9.03.54

initscripts.spec
=> [RHEL6] Rebase to 9.03.55

initscripts.spec
=> [RHEL6] Rebase to 9.03.56

initscripts.spec
To fix the latest regression discovered.
=> [RHEL6] Rebase to 9.03.58

sysconfig/network-scripts/network-functions
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1408219
Kudos Beniamino Galvani
=> use dbus instead of nmcli to make ifup/ifdown faster

Makefile
autorelabel was moved to selinux package
=> Makefile: remove autorelabel stuff

po/initscripts.pot, po/xgettext_sh.py
=> Fix initscripts.pot

rwtab
=> rwtab: add /var/lib/systemd/timers

initscripts.spec, rwtab
I will add more commits here later, this PR is for tracking additional changes.
=> [RHEL-7] Additional changes for RHEL-7.4

initscripts.spec, rc.d/init.d/functions, sysconfig/network-scripts/ifdown-eth
Related to \#84 (I merged it too soon)... :-/
=> [RHEL-7] Additional changes for RHEL-7.4 - part 2

initscripts.spec
Rebase for RHEL-7.4. Change only to `initscripts.spec` file.
=> [RHEL-7] Rebase to 9.49.38

sysconfig/network-scripts/ifup
Based on on RFE from [BZ #1437034](https://bugzilla.redhat.com/show_bug.cgi?id=1437034).
=> ifup: add support for VLAN_EGRESS_PRIORITY_MAP

examples/networking/ifcfg-eth-dhcp, sysconfig.txt, sysconfig/network-scripts/ifup, sysconfig/network-scripts/ifup-eth, sysconfig/network-scripts/network-functions, systemd/rhel-readonly
These are the additional changes proposed to RHEL-7.4 Beta compose.
=> [RHEL-7.4] Additional changes for beta-compose

initscripts.spec
=> [RHEL-7.4] Rebase to 9.49.39

initscripts.spec
=> [Fedora 26] Rebase to 9.71-1

initscripts.spec
=> [Fedora 26] Rebase to 9.72-1

Makefile
=> Makefile: fix whitespace error in commit b119d37d1

initscripts.spec
=> [Rawhide] 9.74 release

Makefile
Again... :sigh: The `make install` should work fine now.
=> Makefile: Fix additional error in commit b119d37d1

initscripts.spec
=> [Rawhide] 9.75 release

initscripts.spec
And again, and [again](https://media.giphy.com/media/Uod1ANyTO3uGQ/giphy.gif)... :D
=> [Rawhide] 9.76 release

Makefile, sysctl.conf.sparc
=> Drop no longer supported SPARC architecture

sysconfig/network-scripts/ifdown-post, sysconfig/network-scripts/ifup-eth, sysconfig/network-scripts/ifup-post
To speed things up, based on patch & comments from:
https://bugzilla.redhat.com/show_bug.cgi?id=1497759
=> [network-scripts] Replace firewall-cmd with DBus calls

sysconfig/network-scripts/ifdown-post, sysconfig/network-scripts/ifup-post
To avoid error messages that were ignored before...
=> network-scripts: forward DBus calls to /dev/null

sysconfig/network-scripts/ifdown-post, sysconfig/network-scripts/ifup-eth, sysconfig/network-scripts/ifup-post
Backport to RHEL-7.5 to resolve [BZ #1497759](https://bugzilla.redhat.com/show_bug.cgi?id=1497759).
=> [RHEL7] network-scripts: firewall-cmd replaced with DBus calls

rc.d/init.d/functions, sysconfig/network-scripts/ifdown-eth, sysconfig/network-scripts/ifup-eth, sysconfig/network-scripts/network-functions
This is a backport to RHEL-7.5, to resolve [BZ #1380496](https://bugzilla.redhat.com/show_bug.cgi?id=1380496).
=> [RHEL7] ifup-eth: wait for STP to complete setup on bridge if $DELAY is not set

rc.d/init.d/functions
This is a backport to resolve [BZ #1455419](https://bugzilla.redhat.com/show_bug.cgi?id=1455419).
=> [RHEL7] Add *.old to list of ignored files

initscripts.spec
=> [RHEL7] 9.49.40-1

sysconfig/network-scripts/ifdown-post, sysconfig/network-scripts/ifup-eth, sysconfig/network-scripts/ifup-post
To avoid some shellcheck warnings...
=> [network-functions] use POSIX forwarding instead of bash-ism

sysconfig/network-scripts/ifdown-post, sysconfig/network-scripts/ifup-eth, sysconfig/network-scripts/ifup-post
=> [RHEL-7] network-functions: use POSIX forwarding instead of bash-ism

initscripts.spec, sysconfig/network-scripts/ifdown-post, sysconfig/network-scripts/ifup-eth, sysconfig/network-scripts/ifup-post
To fix previously introduced regression & issue.
=> [RHEL-7.5] Latest commits backport

initscripts.spec
=> [RHEL6] 9.03.59 release

initscripts.spec
https://fedoraproject.org/wiki/Packaging:C_and_C%2B%2B#BuildRequire
=> spec: add gcc to BuildRequires

sysconfig.txt
Docs for stuff I added in #2, #6, and #16.
=> Lots of documentation

rc.d/init.d/network
More info: https://bugzilla.redhat.com/show_bug.cgi?id=1554690
=> network.service: 'reload' removed

initscripts.spec
Sources & URL moved to Github...
=> RHEL-6 | 9.03.61

po/xgettext_sh, po/xgettext_sh.py
Also, the code has been fixed to comply with PEP8 specification.
More info: https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3
=> po/xgettext_sh*: converted to use to python3

po/xgettext_sh.py
The tabs & spaces mixture caused bad script conversion and breaking the script completely...
=> po/xgettext_sh.py: fix for indentation of previous commit

initscripts.spec
For F28, before we merge the work for Rawhide (F29).
=> [Fedora] 9.80 release

initscripts.spec
=> RHEL-7 | 9.49.42

Makefile, initscripts.spec
https://bugzilla.redhat.com/show_bug.cgi?id=1585321
=> Fix for conflicting files in Rawhide

network-scripts/ifdown-post, network-scripts/ifup-eth, network-scripts/ifup-post
See https://bugzilla.redhat.com/show_bug.cgi?id=1586284 for more info.
=> network-scripts: fix setting of firewall ZONE

Makefile, src/rename_device.c, src/usernetctl.c
Some warnings were shown only in Koji. This PR fixes/supresses them.
=> Additional warnings suppressed/fixed

initscripts.spec
=> [Rawhide] New release - 9.83

initscripts.spec
We have finally reached a new major milestone with initscripts, and to make it more visible we are making a new major release... :)
=> [10.00] New major release

initscripts.spec
=> [RHEL-7] 9.44.45 release

etc/rc.d/init.d/network, network-scripts/ifdown, network-scripts/ifup
We should get into F29 as soon as possible.
=> ifup/ifdown: deprecation warnings for 'network-scripts' added

initscripts.spec
=> [RHEL-8] 10.00.1 release

etc/rc.d/init.d/network, network-scripts/ifdown, network-scripts/ifup
We better not pollute/break user's existing scripts, if they depend on stdout output of network scripts.
=> network/ifup/ifdown: deprecations warnings redirected to stderr

etc/rc.d/init.d/network, network-scripts/ifdown, network-scripts/ifup
=> [RHEL-8] network/ifup/ifdown: deprecations warnings redirected to stderr

initscripts.spec
=> [Fedora] New release 10.01

initscripts.spec
See https://bugzilla.redhat.com/show_bug.cgi?id=1584317 for more info.
=>  Fix file permissions for /var/log/dmesg*

Makefile, initscripts.spec
Resolve problem when wasn't installed chkconfig package. BZ #1716386
=> Create symlink (/etc/init.d) to /etc/rc.d/init.d

doc/sysconfig.txt, network-scripts/ifup-tunnel, network-scripts/network-functions
Add option for IPv6 GRE tunnel.
Resolve: https://bugzilla.redhat.com/show_bug.cgi?id=1691552
=> Add ip6gre tunnel option

network-scripts/network-functions
https://bugzilla.redhat.com/show_bug.cgi?id=1404265
Resolves: rhbz#1404265
=> network-function: bridges are created by ifup-eth

etc/rc.d/init.d/network
Resolves: [https://bugzilla.redhat.com/show_bug.cgi?id=1738578](url)
=> network: don't fail with IFDOWN_ON_SHUTDOWN

usr/sbin/service
=> Change spacing of service file to folow spacing of project

usr/sbin/service
=> Workaround for service network stop cmd

sysconfig/network-scripts/network-functions-ipv6
=> ipv6_wait_tentative(): Fix error message

etc/rc.d/init.d/functions
=> Remove deprecated option -m of pidof

etc/rc.d/init.d/network
Sugested by @lnykryn
Related to issue #300
=> Replace grep -EL with subshell since -L changed behaviour

initscripts.spec, sysconfig/network-scripts/ifup-eth
backport of: 0be531981e4066af4d657715530ff905cea02fe9
Resolves:    #1609687
=> ifup-eth: Switch to bc utility, which supports floating point computations.

network-scripts/network-functions
set umask in case resolv.conf doesn't exist
=> Maintain permisision to set umask

network-scripts/network-functions
=> Add ethtool into required packages for network-scripts - Olav Vitters

initscripts.spec
=> Add info into specfile about readonly-root deprecation

usr/sbin/service
=> service: Prevent variables from globbing

usr/sbin/service
https://github.com/systemd/systemd/blob/master/src/systemctl/systemctl.c#L957-L1031
Resolves: #1894492
=> service: catch unsupported action keywords

.ci/check-shell.sh, .ci/exception-list.txt, .ci/functions.sh, .ci/script-list.txt
**New features**:
* add ability to ignore specific warnings
* ci test files containing shebang #!/bin/bash or #!/bin/sh
* ci test files with .sh extension
* add ability to use inline comments in list files
* use of colors in output
* make code cleaner
**Bug fixes**:
* ci now checks only shell scripts
=> ci: Rework of shell ci

network-scripts/network-functions
This patch fixes issue, when interface wasn't bring up.
Fixes issue introduced in #354
=> network: fix set_link_up()

doc/sysconfig.txt
=> doc: Documents ifcfg option LINKSTATUS

doc/sysconfig.txt
Add documentation for RES_OPTIONS.
Fixes: #320
=> doc: Documents RES_OPTIONS option

network-scripts/network-functions
=> network: fix condition in set_link_up()

.packit.yml
Packit will run copr-build on every PR.
Replaces #292
=> ci: Onboard initscripts to Packit

src/rename_device.c
There are 2 cases where this might be useful.
* On machines with initrd build without dracut-network, you can now
still use ifname option
* On older kernels where double renaming was allowed, normal system
replaced the name set by initrd.
=> rename_device: also support dracut-style kernel cmdline configuration

sysconfig/network-scripts/ifdown-eth, sysconfig/network-scripts/ifup-eth
minor change to enable veth ifcfg files.
been using it in my environment for some time and found it helpful, maybe some else will too.
first pr to public repo, so if i''ve skipped a required procedure please let me know.
=> ifup can create veth devices

initscripts.spec
Add strong relation between initscripts and initscripts-service.
Also update Obsoletes of initscripts package.
=> spec: Update relation between initscripts and initscripts-service

Makefile
This is fixing long term issue #384
=> spec: Fix issue with $NEXT_VERSION

.github/workflows/shellcheck_test.yml
Use new upstream of csdiff. Fixes #389
=> ci: Update path to csdiff repository

.github/workflows/check-shell.sh, .github/workflows/functions.sh, .github/workflows/shellcheck_test.yml
example:
```diff
@@ Shellcheck test summary @@
- added issues: 0
+ solved issues: 7
./.github/workflows/check-shell.sh ./.github/workflows/functions.sh
```
=> ci: Output shellcheck results using PR comments

.mergify.yml, README.md
This change has been made by @jamacku from https://mergify.io config editor.
=> ci(Mergify): configuration update

network-scripts/ifup-routes
=> ifup-routes: Log when using `ip $type replace`

.github/workflows/shellcheck_test.yml
=> ci: remove testing branch from `shellcheck_test.yml`

network-scripts/ifup-routes
Quotes were introduced in a71dcfd392cc1022c255208fdd94a0fc6c13ceb0
Resolves: #2044189
=> ifup-routes: Revert quotes

initscripts.spec
=> (#2057917) spec: Update initscripts Obsoletes

.mergify.yml
This change has been made by @jamacku from https://mergify.com config editor.
=> ci(Mergify): configuration update ; `master` -> `main`

usr/libexec/readonly-root
=> (RHEL-23313) Fix parsing of statetab files when it contains space characters
